# Model arguments
model_name_or_path: outputs/star_graph/teacherforcing_gpt2_12x6x384/checkpoint-500
model_revision: main
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  nnheui/star-d2_p5_n50: 1.0
dataset_splits:
- train
- validation
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: steps
eval_steps: 500
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: gpt2-dpo-dutch
learning_rate: 0.000001
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 20
optim: adamw_torch
output_dir: outputs/star_graph/dpo_gpt2_12x6x384
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
push_to_hub: false
save_strategy: "steps"
save_steps: 500
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
- none
tokenizer_name: gpt